# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: SvelteKit

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3
    - name: Setup SvelteKit
      uses: actions/setup-node@v3
      with:
        node-version: 19.3.x
        cache: "npm"

    - name: Execute Unit tests
    - run: npm ci
    - run: npm run test:unit
